In [2]:
X = [20, 3, 1 , 3, 6, 4]
sum = 0
for x_i in X:
  sum += x_i
x_hat = sum/len(X)
x_hat

6.166666666666667

In [3]:
def mean(X):
  sum = 0
  for x_i in X:
    sum += x_i
  x_hat = sum/len(X)
  return x_hat

mean(X)

6.166666666666667

In [4]:
pip install numpy

In [6]:
import numpy as np
X = np.array([20, 3, 1 , 3, 6, 4])
x_hat = X.sum()/ X.size
x_hat
print(x_hat)

6.166666666666667


In [7]:
X.mean()

np.float64(6.166666666666667)

In [8]:
X.min()

np.int64(1)

In [9]:
X.max()

np.int64(20)

In [12]:
D = np.random.random((6,4))
D

array([[0.30897716, 0.643766  , 0.51895639, 0.51804418],
       [0.35204061, 0.58194237, 0.87984281, 0.76529434],
       [0.47292151, 0.58203822, 0.98998323, 0.27614614],
       [0.87555894, 0.44553404, 0.05402121, 0.72492813],
       [0.37690042, 0.15644132, 0.13775865, 0.76156223],
       [0.55811659, 0.46744846, 0.76107546, 0.65306958]])

In [14]:
D.shape

(6, 4)

In [15]:
D[0,0]

np.float64(0.3089771617390822)

In [16]:
D[4,2]

np.float64(0.1377586455696881)

In [17]:
D[6,2]

IndexError: index 6 is out of bounds for axis 0 with size 6

In [18]:
column_0_loop = []
for row in D:
    column_0_loop.append(row[0])
column_0_loop

[np.float64(0.3089771617390822),
 np.float64(0.3520406058254162),
 np.float64(0.4729215134075202),
 np.float64(0.8755589423064226),
 np.float64(0.3769004166956237),
 np.float64(0.5581165863318033)]

In [19]:
D

array([[0.30897716, 0.643766  , 0.51895639, 0.51804418],
       [0.35204061, 0.58194237, 0.87984281, 0.76529434],
       [0.47292151, 0.58203822, 0.98998323, 0.27614614],
       [0.87555894, 0.44553404, 0.05402121, 0.72492813],
       [0.37690042, 0.15644132, 0.13775865, 0.76156223],
       [0.55811659, 0.46744846, 0.76107546, 0.65306958]])

In [22]:
column_0 = [row[0] for row in D]
column_0

[np.float64(0.3089771617390822),
 np.float64(0.3520406058254162),
 np.float64(0.4729215134075202),
 np.float64(0.8755589423064226),
 np.float64(0.3769004166956237),
 np.float64(0.5581165863318033)]

In [23]:
D[:,0]

array([0.30897716, 0.35204061, 0.47292151, 0.87555894, 0.37690042,
       0.55811659])

In [24]:
D[3, :]

array([0.87555894, 0.44553404, 0.05402121, 0.72492813])

In [25]:
D.shape

(6, 4)

In [26]:
D[:, [0,2,3]]

array([[0.30897716, 0.51895639, 0.51804418],
       [0.35204061, 0.87984281, 0.76529434],
       [0.47292151, 0.98998323, 0.27614614],
       [0.87555894, 0.05402121, 0.72492813],
       [0.37690042, 0.13775865, 0.76156223],
       [0.55811659, 0.76107546, 0.65306958]])

In [28]:
D[:, [3,2,0]]

array([[0.51804418, 0.51895639, 0.30897716],
       [0.76529434, 0.87984281, 0.35204061],
       [0.27614614, 0.98998323, 0.47292151],
       [0.72492813, 0.05402121, 0.87555894],
       [0.76156223, 0.13775865, 0.37690042],
       [0.65306958, 0.76107546, 0.55811659]])

In [27]:
D[[2,3,4],:]

array([[0.47292151, 0.58203822, 0.98998323, 0.27614614],
       [0.87555894, 0.44553404, 0.05402121, 0.72492813],
       [0.37690042, 0.15644132, 0.13775865, 0.76156223]])

In [29]:
D[[0,2,3], [0,2]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [30]:
D[[0,2,3],[0,2,3]]

array([0.30897716, 0.98998323, 0.72492813])

In [31]:
D

array([[0.30897716, 0.643766  , 0.51895639, 0.51804418],
       [0.35204061, 0.58194237, 0.87984281, 0.76529434],
       [0.47292151, 0.58203822, 0.98998323, 0.27614614],
       [0.87555894, 0.44553404, 0.05402121, 0.72492813],
       [0.37690042, 0.15644132, 0.13775865, 0.76156223],
       [0.55811659, 0.46744846, 0.76107546, 0.65306958]])

In [32]:
rows = [0, 2, 3]  # Rows to select
cols = [1, 3]  # Columns to select

print(D[np.ix_(rows, cols)])

[[0.643766   0.51804418]
 [0.58203822 0.27614614]
 [0.44553404 0.72492813]]


In [34]:
X0 = D[:, 0]
X1 = D[:, 1]
X2 = D[:, 2]

In [35]:
np.dot(X0, X2)

np.float64(1.4622593212272255)

In [37]:
d1 = np.linalg.norm(X2-X0, 1)
d1

np.float64(2.5184815333822566)

In [39]:
d2 = np.linalg.norm(X2-X0, 2)
d2

np.float64(1.167614921367676)

In [40]:
4*X0

array([1.23590865, 1.40816242, 1.89168605, 3.50223577, 1.50760167,
       2.23246635])

In [42]:
two_norm_of_X0 = np.linalg.norm(X0, 2)
normalized_X0 = X0 / two_norm_of_X0
print(X0)
print(normalized_X0)

[0.30897716 0.35204061 0.47292151 0.87555894 0.37690042 0.55811659]
[0.23958156 0.27297305 0.36670437 0.6789103  0.2922494  0.43276481]


In [43]:
I = np.random.randint(-2, 20, (5,7), dtype=np.int32)
print(I)

[[ 7 14  8 11  9 15 15]
 [-2  5  3  5 16 11 12]
 [12 19  3  3  8  0  7]
 [ 4 19 -2 17 -1 11 10]
 [15 11  5  2 10  1 11]]


In [46]:
I - np.array([1,2,3,4,5,6,7])

array([[ 6, 12,  5,  7,  4,  9,  8],
       [-3,  3,  0,  1, 11,  5,  5],
       [11, 17,  0, -1,  3, -6,  0],
       [ 3, 17, -5, 13, -6,  5,  3],
       [14,  9,  2, -2,  5, -5,  4]])

In [47]:
I

array([[ 7, 14,  8, 11,  9, 15, 15],
       [-2,  5,  3,  5, 16, 11, 12],
       [12, 19,  3,  3,  8,  0,  7],
       [ 4, 19, -2, 17, -1, 11, 10],
       [15, 11,  5,  2, 10,  1, 11]], dtype=int32)

In [48]:
I.mean()

np.float64(8.4)

In [49]:
I.mean(axis=0)

array([ 7.2, 13.6,  3.4,  7.6,  8.4,  7.6, 11. ])

In [50]:
I.mean(axis=1)

array([11.28571429,  7.14285714,  7.42857143,  8.28571429,  7.85714286])

In [51]:
D

array([[0.30897716, 0.643766  , 0.51895639, 0.51804418],
       [0.35204061, 0.58194237, 0.87984281, 0.76529434],
       [0.47292151, 0.58203822, 0.98998323, 0.27614614],
       [0.87555894, 0.44553404, 0.05402121, 0.72492813],
       [0.37690042, 0.15644132, 0.13775865, 0.76156223],
       [0.55811659, 0.46744846, 0.76107546, 0.65306958]])

In [53]:
D.mean(axis=0)

array([0.49075254, 0.4795284 , 0.55693963, 0.61650743])

In [54]:
D-D.mean(axis=0)

array([[-0.18177538,  0.1642376 , -0.03798323, -0.09846326],
       [-0.13871193,  0.10241397,  0.32290319,  0.14878691],
       [-0.01783102,  0.10250982,  0.43304361, -0.34036129],
       [ 0.3848064 , -0.03399436, -0.50291842,  0.1084207 ],
       [-0.11385212, -0.32308708, -0.41918098,  0.14505479],
       [ 0.06736405, -0.01207994,  0.20413584,  0.03656215]])

In [55]:
I

array([[ 7, 14,  8, 11,  9, 15, 15],
       [-2,  5,  3,  5, 16, 11, 12],
       [12, 19,  3,  3,  8,  0,  7],
       [ 4, 19, -2, 17, -1, 11, 10],
       [15, 11,  5,  2, 10,  1, 11]], dtype=int32)

In [56]:
I.transpose()

array([[ 7, -2, 12,  4, 15],
       [14,  5, 19, 19, 11],
       [ 8,  3,  3, -2,  5],
       [11,  5,  3, 17,  2],
       [ 9, 16,  8, -1, 10],
       [15, 11,  0, 11,  1],
       [15, 12,  7, 10, 11]], dtype=int32)

write some code to mean center along the rows. 

In [57]:
(I.transpose() - I.mean(axis=1)).transpose()

array([[ -4.28571429,   2.71428571,  -3.28571429,  -0.28571429,
         -2.28571429,   3.71428571,   3.71428571],
       [ -9.14285714,  -2.14285714,  -4.14285714,  -2.14285714,
          8.85714286,   3.85714286,   4.85714286],
       [  4.57142857,  11.57142857,  -4.42857143,  -4.42857143,
          0.57142857,  -7.42857143,  -0.42857143],
       [ -4.28571429,  10.71428571, -10.28571429,   8.71428571,
         -9.28571429,   2.71428571,   1.71428571],
       [  7.14285714,   3.14285714,  -2.85714286,  -5.85714286,
          2.14285714,  -6.85714286,   3.14285714]])

In [58]:
var_x0 = np.sum((X0-X0.mean())**2) / (X0.size-1)
print(var_x0)

0.04363548446176323


In [59]:
np.var(X0)

np.float64(0.036362903718136025)

In [61]:
np.var(X0)*(X0.size)/(X0.size-1)

np.float64(0.04363548446176323)

In [62]:
np.var(X0, ddof=1)

np.float64(0.04363548446176323)

Create a matrix M of 10 rows and 8 columns, fill with it with random values.
Calculate the multi dimensional mean (represent the multi dimensional mean as a vector)
Calculate the min, max, variance and SD of each attribute.
Create matrix R with range normalized data.
Create matrix Z with z-scores.

In [70]:
M = np.random.rand(10,8)
mean_vec = M.mean(axis=0)
print(mean_vec)

[0.49558442 0.32646772 0.45076541 0.38954166 0.63665097 0.56877212
 0.47653808 0.40108763]


In [72]:
np.min(M, axis=0)

array([0.11280741, 0.08966087, 0.1410082 , 0.01093353, 0.15558781,
       0.11883575, 0.04935441, 0.02525559])

In [73]:
np.max(M, axis=0)

array([0.70993927, 0.8123883 , 0.75990353, 0.81275812, 0.99960456,
       0.88300554, 0.86622964, 0.81164111])

In [76]:
variance_vec = np.var(M, axis=0, ddof=1)
variance_vec

array([0.0346752 , 0.04849062, 0.0427172 , 0.07153721, 0.08673694,
       0.05740044, 0.07981537, 0.08078342])

In [78]:
std_v = np.std(M, axis=0, ddof=1)
std_v

array([0.18621277, 0.22020585, 0.20668139, 0.26746441, 0.29451136,
       0.23958388, 0.28251614, 0.28422423])

In [81]:
R = (M - np.min(M, axis=0))/(np.max(M, axis=0) - np.min(M, axis=0))
R

array([[0.54948051, 0.33242446, 0.23266419, 0.02274631, 0.29113719,
        0.        , 0.1641185 , 0.7223675 ],
       [1.        , 0.03046347, 0.41329211, 1.        , 0.        ,
        0.69280339, 1.        , 0.83626644],
       [0.6630114 , 0.57831029, 0.42103237, 0.38091286, 0.93868811,
        0.85327131, 0.36089174, 0.26748068],
       [0.97105811, 0.1680863 , 1.        , 0.62914852, 0.45506103,
        0.87870076, 0.        , 1.        ],
       [0.7909574 , 0.        , 0.62852649, 0.22951326, 1.        ,
        0.48955278, 0.92112254, 0.19081889],
       [0.39369745, 0.51032624, 0.69084526, 0.35713782, 0.38853007,
        1.        , 0.57097021, 0.68800506],
       [0.47456074, 1.        , 0.72387653, 0.        , 0.22330347,
        0.46395044, 0.67961328, 0.23021172],
       [0.60268665, 0.3423342 , 0.05374733, 0.80049029, 0.78605786,
        0.18384546, 0.11798645, 0.77424839],
       [0.96480719, 0.2199672 , 0.84101732, 0.54825142, 0.65746691,
        0.61998147, 0.746180

In [83]:
Z = (M - mean_vec)/std_v
Z

array([[-0.29356041,  0.01564636, -0.80201913, -1.34735526, -0.79908122,
        -1.87799096, -1.03753129,  0.67632272],
       [ 1.1511286 , -0.97540585, -0.26113941,  1.5823281 , -1.6334282 ,
         0.33175459,  1.37936032,  0.99145587],
       [ 0.07050115,  0.82265686, -0.23796164, -0.27361709,  1.05668359,
         0.8435784 , -0.46857552, -0.58224837],
       [ 1.05832012, -0.52372032,  1.49572303,  0.47056212, -0.32930489,
         0.92468743, -1.51206819,  1.44447037],
       [ 0.48078791, -1.07538859,  0.38336735, -0.72749401,  1.23239247,
        -0.31652764,  1.15129179, -0.79435457],
       [-0.79311275,  0.59952955,  0.56997727, -0.34489165, -0.5199707 ,
         1.31157996,  0.13885135,  0.58124947],
       [-0.53380699,  2.20666517,  0.66888748, -1.41554582, -0.99348049,
        -0.39818811,  0.45298501, -0.68536333],
       [-0.1229433 ,  0.04817066, -1.33777521,  0.98422314,  0.61927266,
        -1.29160281, -1.17091881,  0.81986565],
       [ 1.03827517, -0.35344442